### ISSUE TITLE
Installation without Docker or Homestead

### ISSUE THREAD

**Issue by jsyzdek** [Labs64/laravel-boilerplate#36]
Is it possible to install this, as-is, on a standard LAMP setup? It gives me errors when I run composer install...

**Comment by r-brown** [comment]
Hi @jsyzdek ,

Sure, this is possible to install Laravel Boilerplate on LAMP. Please make sure that system requirements are met: https://github.com/Labs64/laravel-boilerplate#system-requirements

May I ask you to provide current version of nodejs and npm installed on your system as well as error log.

Best, R.B.

**Comment by jsyzdek** [comment]
Hello @r-brown ,

After your reply, I verified the requirements are installed. I have Nodejs v8.9.4 and PHP v7.0.22. 

Attached is a screenshot of the error I received after running "composer install" with and without --prefer-dist. Please forgive me, as I'm not as well versed with composer yet.

Thanks!
JS

PS. I am aware of the root warning, but this is going to be a locked-down dev machine, not for production so I'm not as concerned about the security issues. :)

![2018-01-29_11-40-38](https://user-images.githubusercontent.com/6536558/35522461-68b1e806-04ea-11e8-8f00-14d2026903be.png)

**Comment by r-brown** [comment]
Hi @jsyzdek ,
I can see from the log that PHP extension `curl` is missing in your PHP installation, which is required for [NetLicensing](https://netlicensing.io) library (we are using this for _membership management_ demo).

In order to resolve this issue, please try to install this extension:
- On CentOS or other yum based package systems:
`$ sudo yum install php-curl`
- On Debian or other apt-get based package systems:
`$ sudo apt-get install php-curl`

**Comment by jsyzdek** [comment]
@r-brown Oh! So sorry. I thought I had done that and I was still getting some other error, but I tried installing php-curl once more and it worked perfectly!

Nevermind the bug, but I hope this helps someone. :)

Cheers!

**Comment by jsyzdek** [comment]
I have one other question, and it probably doesn't need its own issue... I installed everything and I see the homepage as expected, but when I click on any of the links at the top (Sign Up, etc), I get a 404. Please forgive me for my ignorance. Should I need to make an htaccess here?
