### ISSUE TITLE
Should add a build passing flag in readme file

### ISSUE THREAD

**Issue by veerajongit** [Labs64/laravel-boilerplate#67]
Travis tag to denote whether master build in passing.

**Comment by mvarendorff** [comment]
Isn't that already there? Would love to do this (still need PRs for hacktoberfest which is also the reason I found this issue here) but I I got confused because there already is a travis badge in the Readme: 

![Travis CI badge](https://user-images.githubusercontent.com/26303198/66304011-9292af00-e8fc-11e9-8f08-0c5d9cfd14d7.png)

Or am I mixing things up completely here?

**Comment by veerajongit** [comment]
> Isn't that already there? Would love to do this (still need PRs for hacktoberfest which is also the reason I found this issue here) but I I got confused because there already is a travis badge in the Readme:
> 
> ![Travis CI badge](https://user-images.githubusercontent.com/26303198/66304011-9292af00-e8fc-11e9-8f08-0c5d9cfd14d7.png)
> 
> Or am I mixing things up completely here?

Yes. Closing this issue. Thanks.
