### ISSUE TITLE
New registered user does not have any role assigned

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#8]
1. assign default role
2. allow role change via user manage

**Comment by v-rudkovskiy** [comment]
1. assign default role
 - [Fixed in Labs64/laravel-boilerplate@5ca01cd](https://github.com/Labs64/laravel-boilerplate/commit/5ca01cdccd634aa37d9688df1a1b2bef379e4196)
2. allow role change via user manage
- [Fixed in Labs64/laravel-boilerplate@9e061e0](https://github.com/Labs64/laravel-boilerplate/commit/9e061e0fdda6550c73359ea194df3274419e6081)
